# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_id', models.SmallIntegerField()),
                ('troop_type', models.CharField(choices=[('SP_T1', 'T1 Spears'), ('SP_T2', 'T2 Spears'), ('BOW_T1', 'T1 Bows'), ('BOW_T2', 'T2 Bows'), ('INF_T1', 'T1 Infantry'), ('INF_T2', 'T2 Infantry'), ('CAV_T1', 'T1 Cavalry'), ('CAV_T2', 'T1 Cavalry'), ('MIX_SP', 'Mixed spears'), ('MIX_BOW', 'Mixed bows'), ('MIX_INF', 'Mixed infantry'), ('MIX_CAV', 'Mixed cav'), ('MIX', 'Kitchen sink')], max_length=100)),
                ('troop_count', models.IntegerField()),
                ('elite_divs_number', models.SmallIntegerField()),
                ('elite_type', models.CharField(choices=[('CAV', 'Anti-Cavalry'), ('INF', 'Anti-Infantry'), ('BOW', 'Anti-Bow')], max_length=100)),
            ],
            options={
                'db_table': 'armies',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_coord', models.SmallIntegerField()),
                ('y_coord', models.SmallIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logreg.Player')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_player', models.CharField(max_length=100)),
                ('target_city', models.CharField(max_length=100)),
                ('x_coord', models.SmallIntegerField()),
                ('y_coord', models.SmallIntegerField()),
                ('N', models.BooleanField(default=False, verbose_name='north')),
                ('NE', models.BooleanField(default=False, verbose_name='northeast')),
                ('E', models.BooleanField(default=False, verbose_name='east')),
                ('SE', models.BooleanField(default=False, verbose_name='southeast')),
                ('S', models.BooleanField(default=False, verbose_name='south')),
                ('SW', models.BooleanField(default=False, verbose_name='southwest')),
                ('W', models.BooleanField(default=False, verbose_name='west')),
                ('NW', models.BooleanField(default=False, verbose_name='northwest')),
            ],
            options={
                'db_table': 'sieges',
            },
        ),
        migrations.CreateModel(
            name='Siege_army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siege_square', models.CharField(choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest'), ('DIR', 'Direct')], max_length=3)),
                ('time_offset', models.DurationField()),
                ('orders', models.CharField(choices=[('occupy', 'occupy'), ('attack', 'attack'), ('blockade', 'blockade'), ('siege', 'siege')], default='occupy', max_length=30)),
                ('army_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siege.Army')),
                ('siege_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siege.Siege')),
            ],
            options={
                'db_table': 'siege_armies',
            },
        ),
        migrations.AddField(
            model_name='army',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siege.City'),
        ),
        migrations.AddField(
            model_name='army',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logreg.Player'),
        ),
    ]
