# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='elite_type',
            field=models.CharField(blank=True, choices=[('CAV', 'Anti-Cavalry'), ('INF', 'Anti-Infantry'), ('BOW', 'Anti-Bow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='army',
            name='troop_type',
            field=models.CharField(choices=[('SP_T1', 'T1 Spears'), ('SP_T2', 'T2 Spears'), ('BOW_T1', 'T1 Bows'), ('BOW_T2', 'T2 Bows'), ('INF_T1', 'T1 Infantry'), ('INF_T2', 'T2 Infantry'), ('CAV_T1', 'T1 Cavalry'), ('CAV_T2', 'T2 Cavalry'), ('MIX_SP', 'Mixed spears'), ('MIX_BOW', 'Mixed bows'), ('MIX_INF', 'Mixed infantry'), ('MIX_CAV', 'Mixed cav'), ('MIX', 'Kitchen sink')], max_length=100),
        ),
    ]
