# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0002_auto_20160910_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='siege_engines',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='army',
            name='wall_engines',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='army',
            name='troop_count',
            field=models.IntegerField(default=0),
        ),
    ]
