# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0004_auto_20160912_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 14, 36, 5, 60755)),
        ),
    ]
