# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0007_auto_20160912_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 10, 0, 20, 58, 722941)),
        ),
    ]
