# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0009_auto_20161028_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='DIR',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 1, 17, 8, 11, 51980)),
        ),
    ]
