# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0012_auto_20161207_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 9, 22, 45, 17, 646246)),
        ),
    ]
