# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0014_auto_20161213_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 17, 17, 51, 760805)),
        ),
    ]
