# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0015_auto_20170108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 3, 16, 26, 473232)),
        ),
    ]
