# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0016_auto_20170515_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 3, 24, 46, 946599)),
        ),
    ]
