# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-20 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege', '0017_auto_20170515_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='away',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siege_army',
            name='time_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 20, 15, 13, 25, 696368)),
        ),
    ]
