# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-14 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0008_auto_20180114_0549'),
        ('siege', '0018_auto_20170520_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege_army',
            name='player_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logreg.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siege',
            name='landing_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 5, 48, 32, 81387)),
        ),
    ]
