apiVersion: v1
kind: Pod
metadata:
  name: strategos
  labels:
    app: strategos
spec:
  containers:
    - name: strategos
      image: gcr.io/strategos-151306/strategos:1.0.3
      ports:
        - containerPort: 8080
          name: strategos
      env:
        - name: STATIC_URL
          value: "http://storage.googleapis.com/strategos/static/"
        - name: PORT
          value: "8080"
        - name: SQLITE_DATA_PATH
          value: "/data"
        - name: LOG_LEVEL
          value: "debug"
      volumeMounts:
        - name: strategos-sqlite-data
          mountPath: /data
  volumes:
    - name: strategos-sqlite-data
      gcePersistentDisk:
        pdName: strategos-sqlite
        fsType: ext4

---

apiVersion: v1
kind: Service
metadata:
  name: strategos-frontend
  labels:
    name: strategos-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: strategos
