# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0004_auto_20161201_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='illyId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
