# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0006_auto_20170515_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='illyId',
            field=models.IntegerField(null=True),
        ),
    ]
