# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('player_alliance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('townid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mapX', models.IntegerField()),
                ('mapY', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towninfo.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Town_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded_on', models.DateTimeField()),
                ('registered_at', models.DateTimeField()),
                ('relocated_at', models.DateTimeField()),
                ('changed_alliance_at', models.DateTimeField()),
                ('renamed_at', models.DateTimeField()),
                ('abandoned_at', models.DateTimeField()),
                ('destroyed_at', models.DateTimeField()),
                ('previous_status', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towninfo.Town')),
            ],
        ),
    ]
